### PR TITLE
Stop using/testing EOLed 3.6 and 3.7, use 3.9 for linting (3.8 EOLs soon)

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Review by jwodder — CHANGES_REQUESTED** [review]
You also need to:

- Update `python_requires` in `setup.cfg`
- Remove `pypy-3.7` in `test.yml`
- Remove `3.7` and `pypy-3.7` in `benchmark.yml`

**Comment by yarikoptic** [comment]
any clue on how to address

```
asv run --show-stderr --python "$ASV_PYTHON" HEAD^-1
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/con/fscacher/actions/runs/9323025437/job/25665310581?pr=91#step:14:3).11.9/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.9/x6[4](https://github.com/con/fscacher/actions/runs/9323025437/job/25665310581?pr=91#step:14:4)/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.9/x[6](https://github.com/con/fscacher/actions/runs/9323025437/job/25665310581?pr=91#step:14:6)4
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.9/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.9/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.9/x64/lib
    FSCACHER_BENCH_TMPDIRS: .:/tmp/nfs:/tmp/vfat
    ASV_PYTHON: 3.11
Couldn't load asv.plugins._mamba_helpers because
No module named 'libmambapy'
```

I thought I found a workaround https://github.com/con/fscacher/pull/91/commits/6a4a3307004043b854cb385b4c4a3c0bca91c799 but seems not

**Comment by jwodder** [comment]
@yarikoptic I think the simplest option for now is to restrict `asv` to `<0.6.2`.

**Comment by yarikoptic** [comment]
What do we do about
Screenshot_20240531-175159
?

I feel like we were in similar situation somewhere else. 
If recall fix, just push please

**Comment by yarikoptic** [comment]
Woohoo, thanks!

**Pull request merged**
