### PR TITLE
Pass unresolved input path to decorated function

### LINKED ISSUE #44: do not resolve path we pass into decorated function?
prompted by investigating https://github.com/dandi/dandisets/issues/38 -- it seems we resolve path which we pass to underlying function:

<details>
<summary>code -- we pass os.realpath resolved path into original function</summary> 

```shell
 86             @wraps(f)
 87             def fingerprinter(path, *args, **kwargs):
 88                 # we need to dereference symlinks and use that path in the function
(Pdb) 
 89                 # call signature
 90                 path_orig = path
 91                 path = op.realpath(path)
 92                 if path != path_orig:
 93                     lgr.log(5, "Dereferenced %r into %r", path_orig, path)
 94                 if op.isdir(path):
 95                     fprint = self._get_dir_fingerprint(path)
 96                 else:
 97                     fprint = self._get_file_fingerprint(path)
 98                 if fprint is None:
 99                     lgr.debug("Calling %s directly since no fingerprint for %r", f, path)
(Pdb) 
100                     # just call the function -- we have no fingerprint,
101                     # probably does not exist or permissions are wrong
102                     ret = f(path, *args, **kwargs)
103                 # We should still pass through if file was modified just now,
104                 # since that could mask out quick modifications.
105                 # Target use cases will not be like that.
106                 elif fprint.modified_in_window(self._min_dtime):
107                     lgr.debug("Calling %s directly since too short for %r", f, path)
108                     ret = f(path, *args, **kwargs)
109                 else:
110                     lgr.debug("Calling memoized version of %s for %s", f, path)
(Pdb) 
111                     # If there is a fingerprint -- inject it into the signature
112                     kwargs_ = kwargs.copy()
113                     kwargs_[fingerprint_kwarg] = fprint.to_tuple() + (
114                         tuple(self._tokens) if self._tokens else ()
115                     )
116  ->                 ret = fingerprinted(path, *args, **kwargs_)
117                 lgr.log(1, "Returning value %r", ret)
118                 return ret
119     
120             # and we memoize actually that function
121             return fingerprinter
(Pdb) p path
'/mnt/backup/dandi/dandisets/000003/.git/annex/objects/64/J4/SHA256E-s8417855886--918e541a92b934d7543acc92981ed0425eadc0d24dcabf9d8e5b44924dbb1046.nwb/SHA256E-s8417855886--918e541a92b934d7543acc92981ed0425eadc0d24dcabf9d8e5b44924dbb1046.nwb'
(Pdb) p path_orig
PosixPath('/mnt/backup/dandi/dandisets/000003/sub-YutaMouse20/sub-YutaMouse20_ses-YutaMouse20-140327_behavior+ecephys.nwb')

```
</details>

we should check on original motivation and either it could/should be avoided!

### PR DESCRIPTION
**Pull request by jwodder**
Closes #44.

### CODE REVIEW

**Comment by yarikoptic** [comment]
what should we do about this one. The issue is outstanding, right?

**Comment by jwodder** [comment]
@yarikoptic Did you see [my comment on the corresponding issue](https://github.com/con/fscacher/issues/44#issuecomment-996785686)?

**Comment by yarikoptic** [comment]
Not back then, sorry - still digesting it.

**Comment by yarikoptic** [comment]
damn -- it passes the tests now but has substantial detrimental effect on dirs benchmarks. Let's see if minimalistic #63 would do any better

**Comment by jwodder** [comment]
Closed in favor of #63.

**Pull request closed without merging**
